### ISSUE TITLE
Extension Point for own analyzers?

### ISSUE THREAD

**Issue by MichaelKetting** [microsoft/infersharp#30]
Hello, 

I've read the announcement on the dev-blog and was wandering, how would one go and use Infer# for writing their one analyzers. In particular there's things like checking that every branch in a method calls a specific method or that a value is only used in a const-fashion, etc. 

Some cases might be interesting to contribute but others could be very business-case-specific and not lend themselves to contribution. So, would it be best to fork Infer# or is there a way for plugging in your own analyzers to be run with the rest of the native analyzers provided by Infer#

Many thanks, Michael

**Comment by xinshiMSFT** [comment]
Hi Michael, if you are thinking of adding custom capabilities, I would suggest fork your own version. Just a caveat that we are working on consolidating the Infer backend https://github.com/microsoft/infersharp/issues/28, you might want to wait until we have completed this step so that you are consuming the latest bits. You can then try to create an extension point in your forked version, or better yet, contribute that directly to the backend.

**Comment by matjin** [comment]
You may also refer to https://fbinfer.com/docs/checker-linters#al-a-declarative-language-for-writing-linters-in-infer which describes how to write additional checkers which plug directly into the Infer backend.

**Comment by MichaelKetting** [comment]
@xinshiMSFT Thank you! Yes, waiting won't a be a problem, right now it's filed under 'cool stuff for future consideration' :) Good to know that you think an extension point could be a worthwhile contribution. That will definitely be considered when we get around to playing with this. 

@matjin Thank you for the link!
