### ISSUE TITLE
GitHub action runs out of memory after 44 minutes of analyzing

### ISSUE THREAD

**Issue by mike-ward** [microsoft/infersharp#51]
Couple of issues here:

- 44 minutes to run
- runs out of memory

https://github.com/mike-ward/Loon/actions/runs/629723358

**Comment by xinshiMSFT** [comment]
Hi Mike! You may run into memory issues if you have really large binary files or the host machines is too slow. With that being said, I just tried running Infer# on your repo locally. The entire analysis took about 30 seconds to complete with no detected issues. This is what I did.

1. Cloned your repo and updated the Avalonia.XX NuGet packages to 0.10.0 because the beta version you are using is not available on my end.
2. Built the Loon solution, which contains Loon and Twitter.
3. I assumed that the binaries you are interested in are _Loon.dll, Loon.pdb, Twitter.dll, Twitter.pdb_, so I only ran the analysis on these only.

You have a lot of binaries and duplicate language variants that are not built from your own code (i.e. Avalonia, Microsoft, System, etc.), which I assume you have no interest in analyzing. If my assumption is correct, you may put an extra step before the analysis to copy those 4 binary files to a separate folder and point Infer# to that instead.

**Comment by xinshiMSFT** [comment]
On a side note, I also ran Infer# on the entire release folder on my local machine. It took about 30 mins. Pretty much all the warnings are from Avalonia.XX.

**Comment by mike-ward** [comment]
Thanks. I thought it might be the case that the issues were in Avalonia. Was looking for a command line way to limit scope. Did not occur to me to just copy them into a different folder.
