### ISSUE TITLE
analysis process is killed without any error message

### ISSUE THREAD

**Issue by hasancemcerit** [microsoft/infersharp#67]
The analysis process is being killed without an explicit message. I have 8GB memory on the container that I am running the analysis on.

Do you have any ideas?

```
...
Unknown instructions:
Ldelema: 1
Ldelem_U2: 1
Mul_Ovf: 1
Conv_Ovf_U2: 1
Conv_Ovf_U4: 1
Conv_Ovf_U8: 1
Ldelem_U4: 2
Conv_Ovf_U1: 2
Initobj: 4
Stobj: 4
Localloc: 4
Ldelem_U1: 4
Constrained: 15
Ldind_U1: 23
Leave: 25
Ldobj: 32
Ldvirtftn: 37
Unbox_Any: 75
Switch: 114
Ldlen: 115
Leave_S: 437
Throw: 577
Ldftn: 1226
Castclass: 4958

Coverage Statistics:

Method successfully translated: 24774 (76%)
Method partially translated: 7674 (24%)
Instructions translated: 1081979 (68%)
Instructions skipped: 511962 (32%)
======================================

-e You may see 'Unable to parse instruction xxx' above. This is expected as we have not yet translated all the CIL instructions, which follow a long tail distribution. We are continuing to expand our .NET translation coverage.

-e Translation completed. Analyzing...

Logs in /app/infer-out/logs
Killed
```

**Comment by xinshiMSFT** [comment]
Hi Hasan, according to the coverage stats, your code base seems quite big. The failure was probably due to the sheer size. A few things you can try:

- _Only analyze your code binaries_. You may have included some third-party libraries which contain both dll and pdb files. Infer# will also analyze those but there is no value to your code.
- _Increase the Docker memory size._ We have not seen any failures from our own testing on fairly large code bases with 12GB of memory. But each repo is different, it may not be a guarantee.
- _Try our [1.1 beta release](https://github.com/microsoft/infersharp/releases/tag/v1.1-beta)._ While are still working on it, a lot of improvements have been made. Either use [WSL2](https://github.com/microsoft/infersharp/blob/main/RUNNING_INFERSHARP_ON_WINDOWS.md) (it has better performance than Docker in general based on our internal testing), or v1.1 Docker beta image:
```
docker pull mcr.microsoft.com/infersharp:v1.1
```

**Comment by hasancemcerit** [comment]
@aayc I was using `sh` to run infersharp.sh using the following command
```
docker run -it --name infer --hostname infer -v myproject:/myproject mcr.microsoft.com/infersharp:v1.1 sh run_infersharp.sh /myproject
```

I've changed to `bash` after your comment, and substitution error is no more. 👍🏻

**Comment by aayc** [comment]
Ah that makes sense, thank you for letting me know 😁
